export const colors = [
  { name: 'red', hexCode: '#FF0000' },
  { name: 'green', hexCode: '#008000' },
  { name: 'blue', hexCode: '#0000FF' },
  { name: 'yellow', hexCode: '#FFFF00' },
  { name: 'purple', hexCode: '#800080' },
  { name: 'orange', hexCode: '#FFA500' },
  { name: 'pink', hexCode: '#FFC0CB' },
  { name: 'brown', hexCode: '#A52A2A' },
  { name: 'teal', hexCode: '#008080' },
  { name: 'navy', hexCode: '#000080' },
  { name: 'lime', hexCode: '#00FF00' },
  { name: 'cyan', hexCode: '#00FFFF' },
  { name: 'magenta', hexCode: '#FF00FF' },
  { name: 'silver', hexCode: '#C0C0C0' },
  { name: 'gold', hexCode: '#FFD700' },
  { name: 'black', hexCode: '#000000' },
];
